# SPDX-FileCopyrightText: 2022 Jorge Martinez Gil
#
# SPDX-License-Identifier: MIT
"""Reproducible benchmark for the NEFUSI Python reference implementation.

Every number printed here is computed live -- nothing is hard-coded.  Results
are written to ``results/benchmark.md`` (a publication-ready table).

IMPORTANT (scientific integrity): this is the *pure-Python reference
implementation*.  It is faithful to the NEFUSI methodology but is NOT a
bit-exact reproduction of the original Java/MOEAFramework pipeline, so absolute
numbers differ from the DaWaK-2021 / JIFS-2022 papers.  In-sample correlations
are optimistic; held-out and multi-objective figures are the meaningful ones.

Run:
    python examples/reproduce.py              # full
    python examples/reproduce.py --quick      # fast smoke run
"""
from __future__ import annotations

import argparse
import os

import numpy as np

from nefusi import NeuroFuzzyAggregator, load_builtin, pearson, spearman
from nefusi.metrics import bootstrap_ci


def baselines(gold, X):
    mean_r = pearson(gold, X.mean(axis=1))
    best_i = int(np.argmax([abs(pearson(gold, X[:, i])) for i in range(X.shape[1])]))
    best_r = pearson(gold, X[:, best_i])
    return mean_r, best_i, best_r


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    maxiter = 20 if args.quick else 80
    popsize = 30 if args.quick else 60

    rows = []

    # ---- Experiment 1: in-domain GeReSiD (train -> validation) -----------
    gtr, Xtr = load_builtin("geresid-training")
    gte, Xte = load_builtin("geresid-validation")
    m = NeuroFuzzyAggregator(random_state=args.seed).fit(
        Xtr, gtr, maxiter=maxiter, popsize=popsize)
    r_tr = pearson(gtr, m.predict(Xtr))
    r_te = pearson(gte, m.predict(Xte))
    rho_te = spearman(gte, m.predict(Xte))
    mr, bi, br = baselines(gte, Xte)
    rows.append(("GeReSiD (in-domain, single-obj.)",
                 f"{r_tr:.3f}", f"{r_te:.3f}", f"{rho_te:.3f}",
                 f"{mr:.3f}", f"m{bi}={br:.3f}", len(m.rules_)))

    # ---- Experiment 2: MC in-sample fit ----------------------------------
    gmc, Xmc = load_builtin("mc-training")
    m2 = NeuroFuzzyAggregator(random_state=args.seed).fit(
        Xmc, gmc, maxiter=maxiter, popsize=popsize)
    r_in = pearson(gmc, m2.predict(Xmc))
    rho_in = spearman(gmc, m2.predict(Xmc))
    mr2, bi2, br2 = baselines(gmc, Xmc)
    rows.append(("Miller-Charles (in-sample)",
                 f"{r_in:.3f}", "-", f"{rho_in:.3f}",
                 f"{mr2:.3f}", f"m{bi2}={br2:.3f}", len(m2.rules_)))

    # ---- Experiment 3: MC -> GeReSiD multi-objective (NEFUSI style) ------
    m3 = NeuroFuzzyAggregator(random_state=args.seed).fit(
        Xmc, gmc, X_val=Xte, y_val=gte, val_weight=0.5,
        maxiter=maxiter, popsize=popsize)
    r3_tr = pearson(gmc, m3.predict(Xmc))
    r3_te = pearson(gte, m3.predict(Xte))
    rho3_te = spearman(gte, m3.predict(Xte))
    rows.append(("MC->GeReSiD (multi-objective)",
                 f"{r3_tr:.3f}", f"{r3_te:.3f}", f"{rho3_te:.3f}",
                 f"{mr:.3f}", f"m{bi}={br:.3f}", len(m3.rules_)))

    # ---- Render table ----------------------------------------------------
    hdr = ("Experiment", "train r", "test r", "test rho",
           "mean base", "best base", "#rules")
    print("\n" + "=" * 92)
    print("NEFUSI Python reference implementation -- live benchmark "
          f"(seed={args.seed}, maxiter={maxiter})")
    print("=" * 92)
    widths = [34, 8, 7, 9, 10, 11, 7]
    line = "  ".join(h.ljust(w) for h, w in zip(hdr, widths))
    print(line)
    print("-" * len(line))
    for r in rows:
        print("  ".join(str(c).ljust(w) for c, w in zip(r, widths)))

    r, lo, hi = bootstrap_ci(gte, m.predict(Xte), "pearson", seed=args.seed)
    print(f"\nGeReSiD in-domain test Pearson 95% CI: [{lo:.3f}, {hi:.3f}]")

    # ---- Write markdown report ------------------------------------------
    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "results")
    os.makedirs(out_dir, exist_ok=True)
    md = os.path.join(out_dir, "benchmark.md")
    with open(md, "w", encoding="utf-8") as fh:
        fh.write("# NEFUSI reference-implementation benchmark\n\n")
        fh.write(f"Generated by `examples/reproduce.py` (seed={args.seed}, "
                 f"maxiter={maxiter}). All numbers computed live.\n\n")
        fh.write("| " + " | ".join(hdr) + " |\n")
        fh.write("|" + "|".join(["---"] * len(hdr)) + "|\n")
        for r in rows:
            fh.write("| " + " | ".join(str(c) for c in r) + " |\n")
        fh.write("\n> Reference implementation; not a bit-exact reproduction "
                 "of the Java MOEA pipeline. See README.\n")
    print(f"\nWrote {md}")


if __name__ == "__main__":
    main()
